### ISSUE TITLE
(Presentation) Nice work!

### ISSUE THREAD

**Issue by CharlesDLandau** [nataliedex/intro-data-capstone-biodiversity#1]
You've got a catchy, visually interesting presentation that checks all the boxes - nice work! I only had a few notes:

- Park Ranger John was an interesting angle for this presentation! I liked it, but it's only appropriate for some audiences. He would not go over well in a client meeting, I think.
- "The difference is only by chance" is not quite correct - "no different than could result from random chance" is closer to the mark.
- Some of the plots could benefit from being relabeled, but overall they look great.

**Comment by nataliedex** [comment]
Thanks for reviewing the project Charles.  I agree with the Park Ranger John angle being a little odd for most situations -- I just wanted something to tie together the 2 portions of the project in a playful way.
